info:
  contact: {}
paths:
  /admin/category:
    get:
      description: 获取分类列表
      parameters:
      - description: token
        in: header
        name: authorization
        type: string
      - description: 请输入当前页,默认第一页
        in: query
        name: page
        type: integer
      - description: 每页多少条数据,默认20条
        in: query
        name: pageSize
        type: integer
      - description: 关键字
        in: query
        name: keyWord
        type: string
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 获取分类列表
      tags:
      - 管理员私有方法
  /admin/problem:
    post:
      description: 添加问题
      parameters:
      - description: token
        in: header
        name: authorization
        type: string
      - description: 问题标题
        in: formData
        name: title
        type: string
      - description: 问题内容
        in: formData
        name: content
        type: string
      - description: 最大内存
        in: formData
        name: max_mem
        type: integer
      - description: 最大运行时间
        in: formData
        name: max_runtime
        type: integer
      - description: 分类id
        in: formData
        name: category_ids
        type: array
      - description: 测试用例
        in: formData
        name: test_cases
        type: array
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 添加一个问题
      tags:
      - 管理员私有方法
  /admin/user-list:
    get:
      consumes:
      - application/json
      description: 获取用户列表
      parameters:
      - description: token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 获取所有用户
      tags:
      - 管理员私有方法
  /problem/detail:
    get:
      description: 获取问题详细信息
      parameters:
      - description: 问题的唯一标识
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 问题详情
      tags:
      - 公共方法
  /problem/list:
    get:
      description: 获取问题列表
      parameters:
      - description: 请输入当前页,默认第一页
        in: query
        name: page
        type: integer
      - description: 每页多少条数据,默认20条
        in: query
        name: pageSize
        type: integer
      - description: 查询的关键字
        in: query
        name: keyWord
        type: string
      - description: 分类的唯一标识
        in: query
        name: category_identity
        type: string
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 获取问题列表
      tags:
      - 公共方法
  /rank-list:
    get:
      description: 排行榜
      parameters:
      - description: 请输入当前页,默认第一页
        in: query
        name: page
        type: integer
      - description: 每页多少条数据,默认20条
        in: query
        name: pageSize
        type: integer
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 用户排行榜
      tags:
      - 公共方法
  /submit-list:
    get:
      description: 获取问题列表
      parameters:
      - description: 请输入当前页,默认第一页
        in: query
        name: page
        type: integer
      - description: 每页多少条数据,默认20条
        in: query
        name: pageSize
        type: integer
      - description: 问题的唯一标识
        in: query
        name: problem_identity
        type: string
      - description: 用户的唯一标识
        in: query
        name: user_identity
        type: string
      - description: 提交的状态【-1-待判断，1-答案正确，2-答案错误，3-运行超时，4-运行超内存】
        in: query
        name: status
        type: integer
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 获取提交记录列表
      tags:
      - 公共方法
  /user/detail:
    get:
      description: 获取用户详细信息
      parameters:
      - description: 用户的唯一标识
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 获取用户详细信息
      tags:
      - 公共方法
  /user/login:
    post:
      description: 用户登录
      parameters:
      - description: 用户名
        in: formData
        name: username
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 公共方法
  /user/register:
    post:
      description: 用户注册
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 确认密码
        in: formData
        name: confirm_password
        required: true
        type: string
      - description: 手机号
        in: formData
        name: phone
        type: string
      - description: 邮箱
        in: formData
        name: mail
        required: true
        type: string
      - description: 验证码
        in: formData
        name: code
        required: true
        type: string
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - 公共方法
  /user/send-code:
    post:
      description: 发送邮箱验证码
      parameters:
      - description: 用户邮箱
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 发送邮箱验证码
      tags:
      - 公共方法
swagger: "2.0"
