info:
  contact: {}
paths:
  /login:
    post:
      description: 用户登录
      parameters:
      - description: 用户名
        in: formData
        name: username
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 公共方法
  /problem-detail:
    get:
      description: 获取问题详细信息
      parameters:
      - description: 问题的唯一标识
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 问题详情
      tags:
      - 公共方法
  /problem-list:
    get:
      description: 获取问题列表
      parameters:
      - description: 请输入当前页,默认第一页
        in: query
        name: page
        type: integer
      - description: 每页多少条数据,默认20条
        in: query
        name: pageSize
        type: integer
      - description: 查询的关键字
        in: query
        name: keyWord
        type: string
      - description: 分类的唯一标识
        in: query
        name: category_identity
        type: string
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 获取问题列表
      tags:
      - 公共方法
    post:
      description: 添加问题
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 添加一个问题
      tags:
      - 公共方法
  /send-code:
    post:
      description: 发送邮箱验证码
      parameters:
      - description: 用户邮箱
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 发送邮箱验证码
      tags:
      - 公共方法
  /submit-list:
    get:
      description: 获取问题列表
      parameters:
      - description: 请输入当前页,默认第一页
        in: query
        name: page
        type: integer
      - description: 每页多少条数据,默认20条
        in: query
        name: pageSize
        type: integer
      - description: 问题的唯一标识
        in: query
        name: problem_identity
        type: string
      - description: 用户的唯一标识
        in: query
        name: user_identity
        type: string
      - description: 提交的状态【-1-待判断，1-答案正确，2-答案错误，3-运行超时，4-运行超内存】
        in: query
        name: status
        type: integer
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 获取提交记录列表
      tags:
      - 公共方法
  /user-detail:
    get:
      description: 获取用户详细信息
      parameters:
      - description: 用户的唯一标识
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 获取用户详细信息
      tags:
      - 公共方法
  /user-list:
    get:
      consumes:
      - application/json
      description: 获取用户列表
      produces:
      - application/json
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 获取所有用户
      tags:
      - 公共方法
swagger: "2.0"
