info:
  contact: {}
paths:
  /problem-list:
    get:
      description: 获取问题列表
      parameters:
      - description: 请输入当前页,默认第一页
        in: query
        name: page
        type: integer
      - description: 每页多少条数据,默认20条
        in: query
        name: pageSize
        type: integer
      - description: 查询的关键字
        in: query
        name: keyWord
        type: string
      - description: 分类的唯一标识
        in: query
        name: category_identity
        type: string
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 获取问题列表
      tags:
      - 公共方法
    post:
      description: 添加问题
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 添加一个问题
      tags:
      - 公共方法
  /user-list:
    get:
      consumes:
      - application/json
      description: 获取用户列表
      produces:
      - application/json
      responses:
        "200":
          description: '{“code”: "200", "msg":"", "data": ""}'
          schema:
            type: string
      summary: 获取所有用户
      tags:
      - 公共方法
swagger: "2.0"
